version: '3.8'

services:
  mongo_database:
    image: mongo:latest
    volumes: 
      #- C:\mongodb\data\db\empty:/data/db
      - ./mongo_db_init/init_db.js:/docker-entrypoint-initdb.d/init-mongo.js 
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=EduTrack
    networks:
      - my-network

  java-app:
    build: 
      context: .
      dockerfile: Dockerfile
      
    container_name: edutrack-javafx-app
    depends_on:
      - mongo_database
    ports:
      - "5900:5900"
    environment:
      - MONGO_URL=mongodb://mongo_database/EduTrack
    networks:
      - my-network

networks:
  my-network:
    driver: bridge