version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: edutrack-mongodb
    volumes: 
      - C:\mongodb\data\db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=edutrack

  java-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: edutrack-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=edutrack